tap "go-task/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "liamg/tfsec"
tap "lucagrulla/cw"
tap "weaveworks/tap"
# CLI for Amazon ECS to manage clusters and tasks for development
brew "amazon-ecs-cli"
# Automatic configure script builder
brew "autoconf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Use AWS IAM credentials to authenticate to Kubernetes
brew "aws-iam-authenticator"
# Official Amazon AWS command-line interface
brew "awscli"
# Simple command-line tool to read AWS CloudWatch logs
brew "awslogs"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Reimplementation of ctags(1)
brew "ctags"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# CLI tool for reading logs from Cloudwatch Logs
brew "cwlogs"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# Docker Credential Helper for Amazon ECR
brew "docker-credential-helper-ecr"
# Maintain consistent coding style between multiple editors
brew "editorconfig"
# Image manipulation library
brew "jpeg"
# TIFF library and utilities
brew "libtiff"
# Image format providing lossless and lossy compression for web images
brew "webp"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Distributed revision control system
brew "git"
# Git extension for versioning large files
brew "git-lfs"
# The official GitLab CI runner written in Go
brew "gitlab-runner"
# Interpreted, interactive, object-oriented programming language
brew "python"
# Library for USB device access
brew "libusb"
# Passphrase entry dialog utilizing the Assuan protocol
brew "pinentry"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Go programming environment (1.12)
brew "go@1.12"
# Library access to GnuPG
brew "gpgme"
# Generic library support script
brew "libtool"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# The Kubernetes package manager
brew "helm"
# Add GitHub support to git on the command-line
brew "hub"
# Regular expressions library
brew "oniguruma"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Host-side of the Universal 2nd Factor (U2F) protocol
brew "libu2f-host"
# GNOME XML library
brew "libxml2"
# XML security library
brew "libxmlsec1"
# YAML Parser
brew "libyaml"
# Fast and user friendly build system
brew "meson"
# Platform built on V8 to build network applications
brew "node"
# Manage multiple Node.js versions
brew "nvm"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Tool for creating identical machine images for multiple platforms
brew "packer"
# Highly capable, feature-rich programming language
brew "perl"
# Python package management tool
brew "poetry"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Implementation of Python 3 in Python
brew "pypy3"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Test SSL/TLS enabled services to discover supported cipher suites
brew "sslscan"
# SSL scanner
brew "sslyze"
# Generate scripting interfaces to C/C++ code
brew "swig"
# Tool to build, change, and version infrastructure
brew "terraform", link: false
# Tool to generate documentation from Terraform modules
brew "terraform-docs"
# Improve Terraform's plan output
brew "terraform_landscape"
# Thin wrapper for Terraform e.g. for locking state
brew "terragrunt"
# Terraform version manager inspired by rbenv
brew "tfenv"
# Linter for Terraform files
brew "tflint"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# YubiKey personalization library and tool
brew "ykpers"
# Simple daemon for locking and unlocking macOS with Yubikey.
brew "yubikeylockd", restart_service: true
# Additional completion definitions for zsh
brew "zsh-completions"
# Static analysis powered security scanner for your terraform code
brew "liamg/tfsec/tfsec"
# The best way to tail AWS Cloudwatch Logs from your terminal
brew "lucagrulla/cw/cw"
# The official CLI for Amazon EKS
brew "weaveworks/tap/eksctl"
cask "avibrazil-rdm"
cask "beyond-compare"
cask "charles"
cask "docker"
cask "font-fira-code"
cask "font-input"
cask "font-iosevka"
cask "font-jetbrains-mono"
cask "font-monoid"
cask "font-office-code-pro"
cask "google-chat"
cask "gpg-suite"
cask "insomnia"
cask "intellij-idea-ce"
cask "keybase"
cask "kitematic"
cask "logitech-control-center"
cask "logitech-options"
cask "osxfuse"
cask "pester"
cask "pock"
cask "postman"
cask "signal"
cask "slack"
cask "telegram"
cask "textmate"
cask "visual-studio-code"
