#!/bin/zsh

# Decrypt Config and Credentials to file
local _cur_dir=$1
local _cred="${_cur_dir}/credentials"
local _enc_cred="${_cred}.asc"
local _conf="${_cur_dir}/config"
local _enc_conf="${_conf}.asc"

if test $_enc_cred -nt $_cred; then
  echo 'Decrypting new AWS Credentials.';
  decrypt_verify "$_enc_cred"

  if ! test -s $_cred; then
    -dot-symlink-update "${_cred}" .aws/credentials
  fi
fi

if test $_enc_conf -nt $_conf; then
  echo 'Decrypting new AWS Config.';
  decrypt_verify "$_enc_conf";

  if ! test -s $_conf; then
    -dot-symlink-update "${_conf}" .aws/config
  fi
fi
