-dot-symlink-update vscode/settings.json "Library/Application Support/Code/User/settings.json"
-dot-symlink-update vscode/vsicons.settings.json "Library/Application Support/Code/User/vsicons.settings.json"
