#!/bin/zsh

if test -z "$(pgrep gpg-agent)" -a -n $(command -v gpg-agent); then
  if ! test -e "${GPG_LOG_FILE}"; then touch "${GPG_LOG_FILE}"; fi

  gpg-agent --daemon --log-file "${GPG_LOG_FILE}"
fi
