#!/bin/zsh

local \
  _src_dir="${PROJECTS}" \
  _p_dir="src" \
  _p_path _p_file _target

_p_path="${_src_dir}/${_p_dir}"
# Strip Path
_target="${_p_path}/${1#$_p_path/}"

edit "${_target}"

export PROJECT="${_target}"

echo "${_target}"
