export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="${DOTFILES_DIR}/.cache/sdkman"
[[ -s "${DOTFILES_DIR}/.cache/sdkman/bin/sdkman-init.sh" ]] && source "${DOTFILES_DIR}/.cache/sdkman/bin/sdkman-init.sh"
