#!/bin/bash

run_hooks_d() {
  local script_dir=$1
  local hook_name=$2

  hook_dir="$script_dir/$hook_name.d"

  if test -d "$hook_dir"; then
    stdin=$(cat /dev/stdin)

    for hook in "$hook_dir/"*; do
      echo "Running $hook_name/$hook hook"
      echo "$stdin" | $hook "$@"

      exit_code=$?

      if test $exit_code -neq 0; then
        exit $exit_code
      fi
    done
  fi

  exit 0
}

run_hooks_d "$(dirname "$0")" "$(basename "$0")"
