#!/bin/zsh

# This script should be saved in a git repo as a hook file, e.g. .git/hooks/pre-receive.
# It looks for scripts in the .git/hooks/pre-receive.d directory and executes them in order,
# passing along stdin. If any script exits with a non-zero status, this script exits.

source "$(dirname "$0")/_lib.sh";

GIT_REPO_HOOK_NAME="$(basename "$0")";

run_hooks_d "$@";
